server:
  port: 8080
  tomcat:
    basedir: .tomcat

spring:
  application:
    name: market-api
  cache:
    type: simple

app:
  ml-api:
    base-url: http://127.0.0.1:8000

market:
  data:
    path: classpath:data/House Price Dataset.csv
